repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [ --fix ]
        exclude: ^docs/demos/
    -   id: ruff-format
        exclude: ^docs/demos/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [numpy, pandas, types-setuptools]
        exclude: ^docs/demos/|^tests/
